version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:8080"
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"